endpoints:
  shutdown:
    enabled: true

spring:
  #Commented out config is for H2 database implementation
  #datasource:
  #  url: jdbc:h2:file:./db/h2-smph-ar
  #  username: sa
  #  password:
  #  driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost/smph_ar
    username: root
    password: 123qwe
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  #h2:
  #  console:
  #    enabled: true
  #    path: /db
  #    settings:
  #      web-allow-others: true

management:
  security:
    enabled: false

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: 123qwe
    key-password: 123qwe
  session:
    timeout: 27000
    cookie:
       max-age: 31536000
security:
  require-ssl: true

logging:
  level:
    ROOT: INFO
    com.smph: debug
  file: log/sm_ar.log