endpoints:
  shutdown:
    enabled: true

management:
  security:
    enabled: false

server:
  port: 8080
  session:
    timeout: 27000
    cookie:
       max-age: 31536000

logging:
  level:
    ROOT: info
    com.sm: debug
  file: log/sm_ar.log