endpoints:
  shutdown:
    enabled: true

spring:
  datasource:
    url: jdbc:h2:file:./db/h2-smph-ar
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /db

management:
  security:
    enabled: false

server:
  port: 8080
  session:
    timeout: 27000
    cookie:
       max-age: 31536000

logging:
  level:
    ROOT: info
    com.sm: debug
  file: log/sm_ar.log