version: '3.3'
services:
  nginx:
    image: nginx:1.10.3
    ports:
    - "8085:80"
    volumes:
    - "./nginx-conf/avengers.conf:/etc/nginx/nginx.conf"
    command: /bin/bash -c "nginx -g 'daemon off;'"