version: '2'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.1
    depends_on:
    - "mysql_avengers"
    restart: always
    ports:
    - "80:8443"
    volumes:
    - "/home/markbbmartinez/dist/log:/log"
    - "/home/markbbmartinez/dist/application.yml:/application.yml"
    environment:
      DATABASE_HOST: mysql_avengers
      DATABASE_USER: smph_user
      DATABASE_PASSWORD: 123qwe
      DATABASE_NAME: smph_ar
      DATABASE_PORT: 3306
  mysql_avengers:
    image: vsamov/mysql-5.1.73
    restart: always
    ports:
    - "3306"
    volumes:
    - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: smph_ar
      MYSQL_USER: smph_user
      MYSQL_PASSWORD: 123qwe
volumes:
  db_data: