version: '3.3'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.0
    ports:
    - "443:8443"
    container_name: sm-ar-avengers
    volumes:
    - "/home/mbmartinez/dist/log:/log"
    - "/home/mbmartinez/dist/db:/db"
