version: '3.3'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.0
    depends_on:
    - "mysql_avengers"
    restart: 'no'
    ports:
    - "443:8443"
    environment:
      DATABASE_HOST: mysql_avengers
      DATABASE_USER: smph_user
      DATABASE_PASSWORD: 123qwe
      DATABASE_NAME: smph_ar
      DATABASE_PORT: 3306
    volumes:
    - "./log:/log"
  mysql_avengers:
    image: mysql:5.7
    restart: always
    ports:
    - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: smph_ar
      MYSQL_USER: smph_user
      MYSQL_PASSWORD: 123qwe
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data:
