version: '2'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.0
    depends_on:
    - "mysql"
    networks:
    - smph
    restart: always
    ports:
    - "443:8443"
    container_name: sm-ar-avengers
    volumes:
    - "/home/markbbmartinez/dist/log:/log"
    - "/home/markbbmartinez/dist/db:/db"
  mysql:
    image: mysql:5.7
    restart: always
    networks:
    - smph
    ports:
    - "3306"
    container_name: msyql-sm-ar-avengers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: smph_ar
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data:
networks:
  smph:
