version: '3.3'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.0
    ports:
    - "443:8443"
    container_name: sm-ar-avengers
    volumes:
    - "./log:/log"
    - "./db:/db"
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - "3306:3306"
    volumes:
    - "./mysql/data/mysql:/var/lib/mysql"