version: '3.3'
services:
  sm-ar:
    depends_on:
    - mysql
    image: exist/sm-ar-avengers:1.0
    ports:
    - "443:8443"
    container_name: sm-ar-avengers
    volumes:
    - "./log:/log"
    - "./db:/db"
  mysql:
    image: mysql:5.7
    ports:
    - "3307:3306"
    container_name: msyql-sm-ar-avengers
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smph_ar
      MYSQL_USER: root
      MYSQL_PASSWORD: 123qwe
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data:
