version: '2'
services:
  sm-ar:
    image: exist/sm-ar-avengers:1.0
    depends_on:
    - "mysql_avengers"
    restart: always
    ports:
    - "443:8443"
    volumes:
    - "/home/markbbmartinez/mysql-test/log:/log"
    - "/home/markbbmartinez/mysql-test/application.yml:/application.yml"
  mysql_avengers:
    image: mysql:5.7
    restart: always
    ports:
    - "3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123qwe
      MYSQL_DATABASE: smph_ar
    volumes:
    - db_data:/var/lib/mysql
volumes:
  db_data: